#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap          15

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#DCD7BA
bspc config normal_border_color \#1F1F28

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam manage=off

setxkbmap -layout us,ru &&
setxkbmap -option "grp:lctrl_lalt_toggle" &&
~/.fehbg &&
picom --daemon &&
~/.config/polybar/launch.sh &&

