[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[colors]
transparent_background_colors = true

[window]
decorations = "None"
opacity = 0.7
padding = {x = 15, y = 15}

[font]
normal = {family = "monospace"}
size = 15.00
