[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
[colors]
transparent_background_colors = true
[window]
decorations = "None"
opacity = 0.85
[font]
normal = {family = "monospace"}
size = 15.00
